# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  vmImage: windows-latest

steps:
- script: echo Hello, world!
  displayName: 'Run a one-line script'

- script: |
- task: UiPathPack@2
  inputs:
    versionType: 'AutoVersion'
    projectJsonPath: '$(Build.SourcesDirectory)'
    orchestratorConnection: 'Test Tenant'
    outputPath: '$(Build.ArtifactStagingDirectory)\Output'
- task: UiPathTest@2
  inputs:
    testTarget: 'TestProject'
    orchestratorConnection: 'Test Tenant'
    testProjectPath: '$(Build.SourcesDirectory)'
    folderName: 'CosmintrainingCICD'
- task: UiPathDeploy@2
  inputs:
    orchestratorConnection: 'Test Tenant'
    packagesPath: '$(Build.ArtifactStagingDirectory)\Output'
    folderName: 'CosmintrainingCICD'
    entryPoints: 'Main.xaml'

